version: 2
registries: 
  dockerhub:
    type: docker-registry 
    url: gcr.io
    token: ${{secrets.TOKEN}}
updates:
  - package-ecosystem: "docker"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates at 9am UTC
      time: "16:30"
      timezone: "Canada/Pacific"