version: 2
registries:
  github-octocat:
    type: git
    url: https://team.googlesource.com/cloud-kubernetes-security-testing/gob-access
    username: x-access-token
    password: ${{secrets.GOB_TOKEN}}
updates:
  - package-ecosystem: "docker"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates at 9am UTC
      time: "16:30"
      timezone: "Canada/Pacific"