version: 2
updates:
  - package-ecosystem: "docker"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates at 9am UTC
      time: "16:30"
      timezone: "Canada/Pacific"